### ISSUE TITLE
Retrieve every possible temperature sensor

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-server-monit#43]
This feature will help to detect the temperature of server components (CPU, GPU, inner box...) and detect component overheat.

Linked to disk drive health check this would potentially allow to determine an index of server health.

**Comment by f-hj** [comment]
In the following folder, you have access to temperature sensors, without the help of other applications.
```
/sys/class/hwmon/hwmon0/
```
```
device/           temp1_crit_alarm  temp2_crit_alarm  temp3_crit_alarm
name              temp1_input       temp2_input       temp3_input
power/            temp1_label       temp2_label       temp3_label
subsystem/        temp1_max         temp2_max         temp3_max
temp1_crit        temp2_crit        temp3_crit        uevent
```

**Comment by Unitech** [comment]
Looks like we can get these values there: cat /sys/class/thermal/thermal_zone*

**Comment by Unitech** [comment]
done via lm-sensors
