### ISSUE TITLE
Error message incorrect - implying virus infection

### ISSUE THREAD

**Issue by danleighton** [keymetrics/pm2-server-monit#69]
Error messages about server problems have an English phrase which is either ambiguous or wrong. This may need to be fixed as it implies a serious problem which may not be true.

The message says:
A NEW EXCEPTION HAS BEEN THROWN
SERVER : <servername> APPLICATION: SERVER
SERVER **_INFECTED_** : <servername>

The problem is the word "infected" which in this context, means "infected with a virus".

Is there an error in the English translation? Should it be the word "affected"? Which means, "when something has had something happen to it". If a server is _not_ infected with a virus, then the message should _definitely_ be this in all cases:

A NEW EXCEPTION HAS BEEN THROWN
SERVER : <servername> APPLICATION: SERVER
SERVER **_AFFECTED_** : <servername>

I hope this is helpful.

**Comment by vmarchaud** [comment]
Fixed in 3.0.0
