### ISSUE TITLE
Save monitored data

### ISSUE THREAD

**Issue by chainhead** [keymetrics/pm2-server-monit#77]
Hi,
This question is generally applicable for all `pm2` monitoring tools. Can `pm2` save monitoring data to a file for later analysis? 

I have a Nginx load balancer in front of 4 NodeJS servers where some APIs are hosted. I have simulation clients (~100) set-up to invoke the APIs and I am interested to see the server performance over a period of say, 8 hours duration.

**Comment by chainhead** [comment]
Thanks! I signed up for the SaaS version. If you won't mind, can you please show me the option to download the historic data? I couldn't locate it.

Also, I recall `pm2` for monitoring MongoDB and PostgreSQL amongst others. Does pm2 plus profile these databases also? With support for history of logs?

**Comment by shubs** [comment]
Hi @chainhead,

1 - You can't download the data but just analyse it, on Metrics Histogram date picker like in the screen below.
<img width="992" alt="screen shot 2018-10-08 at 4 01 24 pm" src="https://user-images.githubusercontent.com/3249538/46613464-9639fd00-cb13-11e8-94df-7a53af1e5c35.png">
2 - Unfortunately the new interface haven't got Database monitoring, but this is coming soon.
3 - For the CPU profiling, you have to stop it yourself.
